language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install pytest

script: pytest

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/cd10585c8f9dc98ebec2
    on_success: change
    on_failure: always
    on_start: never

jobs:
  include:
    - stage: deploy
      python: "3.6"
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install python-semantic-release
        - semantic-release publish
        - bash mark_implemented_functions.sh